# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 07:14
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Letting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Unpublished'), (1, 'Published')])),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('address_1', models.CharField(max_length=100)),
                ('address_2', models.CharField(blank=True, max_length=100, null=True)),
                ('address_3', models.CharField(blank=True, max_length=100, null=True)),
                ('town_city', models.CharField(max_length=50)),
                ('county', models.CharField(max_length=50)),
                ('postcode', models.CharField(max_length=10)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('display_address', models.CharField(blank=True, max_length=200, null=True)),
                ('bedrooms', models.IntegerField()),
                ('en_suites', models.IntegerField()),
                ('receptions', models.IntegerField()),
                ('details', models.TextField()),
                ('summary', models.TextField(max_length=2000)),
                ('garden', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('retirement', models.BooleanField(default=False)),
                ('rental', models.DecimalField(decimal_places=2, max_digits=11)),
                ('period', models.IntegerField(choices=[(1, 'Weekly'), (2, 'Monthly'), (3, 'Annually')])),
                ('type_of_let', models.IntegerField(choices=[(1, 'Long Term'), (2, 'Short Term'), (3, 'Student')])),
                ('furnished', models.BooleanField(default=False)),
                ('house_share', models.BooleanField(default=False)),
                ('let_agreed', models.BooleanField(default=False)),
                ('available_at', models.DateTimeField()),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homes.PropertyType')),
            ],
            options={
                'verbose_name': 'property',
                'verbose_name_plural': 'properties',
            },
            managers=[
                ('filtered', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='LettingContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('more_details', models.BooleanField(default=True)),
                ('view_property', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=10)),
                ('forename', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=2000)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=50)),
                ('postcode', models.CharField(max_length=10)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homes_to_let.Letting')),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contacts',
            },
        ),
        migrations.CreateModel(
            name='LettingFavourite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homes_to_let.Letting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LettingFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_order', models.IntegerField()),
                ('text', models.CharField(max_length=200)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homes_to_let.Letting')),
            ],
            options={
                'verbose_name': 'feature',
                'verbose_name_plural': 'features',
            },
        ),
        migrations.CreateModel(
            name='LettingMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Unpublished'), (1, 'Published')])),
                ('description', models.CharField(max_length=200)),
                ('attachment', models.FileField(upload_to='media/')),
                ('media_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homes.MediaType')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homes_to_let.Letting')),
            ],
            options={
                'verbose_name': 'media item',
                'verbose_name_plural': 'media items',
            },
        ),
        migrations.CreateModel(
            name='LettingNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homes_to_let.Letting')),
            ],
            options={
                'verbose_name': 'note',
                'verbose_name_plural': 'notes',
            },
        ),
        migrations.CreateModel(
            name='LettingPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Unpublished'), (1, 'Published')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_order', models.IntegerField()),
                ('caption', models.CharField(max_length=200)),
                ('attachment', models.ImageField(upload_to='pictures/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homes_to_let.Letting')),
            ],
            options={
                'verbose_name': 'picture',
                'verbose_name_plural': 'pictures',
            },
        ),
    ]
