# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 09:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0002_branch'),
        ('homes_to_let', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lettingfavourite',
            options={'verbose_name': 'favourite', 'verbose_name_plural': 'favourites'},
        ),
        migrations.AddField(
            model_name='letting',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='homes.Branch'),
            preserve_default=False,
        ),
    ]
