# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0002_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Letting'), (2, 'Sale')])),
                ('label', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=11)),
            ],
        ),
    ]
