# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0003_searchprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchprice',
            name='price',
            field=models.IntegerField(),
        ),
    ]
