# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-07 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0004_auto_20170729_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='key',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
