# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-14 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0005_alert_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='key',
            field=models.CharField(max_length=40),
        ),
    ]
