# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-18 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0007_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('keywords', models.CharField(max_length=500)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
    ]
