# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-25 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0009_auto_20170925_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='label',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
